/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.CarEntries;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CarEntriesRecord extends UpdatableRecordImpl<CarEntriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.car_entries.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.car_entries.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.car_entries.session_id</code>.
     */
    public void setSessionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.car_entries.session_id</code>.
     */
    public Long getSessionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.car_entries.team_id</code>.
     */
    public void setTeamId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.car_entries.team_id</code>.
     */
    public Long getTeamId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.car_entries.class_id</code>.
     */
    public void setClassId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.car_entries.class_id</code>.
     */
    public Long getClassId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.car_entries.car_model_id</code>.
     */
    public void setCarModelId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.car_entries.car_model_id</code>.
     */
    public Long getCarModelId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.car_entries.number</code>.
     */
    public void setNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.car_entries.number</code>.
     */
    public String getNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.car_entries.tire_supplier</code>.
     */
    public void setTireSupplier(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.car_entries.tire_supplier</code>.
     */
    public String getTireSupplier() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarEntriesRecord
     */
    public CarEntriesRecord() {
        super(CarEntries.CAR_ENTRIES);
    }

    /**
     * Create a detached, initialised CarEntriesRecord
     */
    public CarEntriesRecord(Long id, Long sessionId, Long teamId, Long classId, Long carModelId, String number, String tireSupplier) {
        super(CarEntries.CAR_ENTRIES);

        setId(id);
        setSessionId(sessionId);
        setTeamId(teamId);
        setClassId(classId);
        setCarModelId(carModelId);
        setNumber(number);
        setTireSupplier(tireSupplier);
        resetChangedOnNotNull();
    }
}
