/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.Cars;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CarsRecord extends UpdatableRecordImpl<CarsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cars.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cars.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.cars.session_id</code>.
     */
    public void setSessionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cars.session_id</code>.
     */
    public Long getSessionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.cars.team_id</code>.
     */
    public void setTeamId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cars.team_id</code>.
     */
    public Long getTeamId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.cars.class_id</code>.
     */
    public void setClassId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cars.class_id</code>.
     */
    public Long getClassId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.cars.manufacturer_id</code>.
     */
    public void setManufacturerId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cars.manufacturer_id</code>.
     */
    public Long getManufacturerId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.cars.number</code>.
     */
    public void setNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cars.number</code>.
     */
    public String getNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.cars.model</code>.
     */
    public void setModel(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cars.model</code>.
     */
    public String getModel() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.cars.tire_supplier</code>.
     */
    public void setTireSupplier(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.cars.tire_supplier</code>.
     */
    public String getTireSupplier() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarsRecord
     */
    public CarsRecord() {
        super(Cars.CARS);
    }

    /**
     * Create a detached, initialised CarsRecord
     */
    public CarsRecord(Long id, Long sessionId, Long teamId, Long classId, Long manufacturerId, String number, String model, String tireSupplier) {
        super(Cars.CARS);

        setId(id);
        setSessionId(sessionId);
        setTeamId(teamId);
        setClassId(classId);
        setManufacturerId(manufacturerId);
        setNumber(number);
        setModel(model);
        setTireSupplier(tireSupplier);
        resetChangedOnNotNull();
    }
}
