/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.Circuits;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class CircuitsRecord extends UpdatableRecordImpl<CircuitsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.circuits.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.circuits.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.circuits.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.circuits.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.circuits.length_meters</code>.
     */
    public void setLengthMeters(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.circuits.length_meters</code>.
     */
    public BigDecimal getLengthMeters() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.circuits.country</code>.
     */
    public void setCountry(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.circuits.country</code>.
     */
    public String getCountry() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.circuits.location</code>.
     */
    public void setLocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.circuits.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.circuits.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.circuits.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CircuitsRecord
     */
    public CircuitsRecord() {
        super(Circuits.CIRCUITS);
    }

    /**
     * Create a detached, initialised CircuitsRecord
     */
    public CircuitsRecord(Long id, String name, BigDecimal lengthMeters, String country, String location, String description) {
        super(Circuits.CIRCUITS);

        setId(id);
        setName(name);
        setLengthMeters(lengthMeters);
        setCountry(country);
        setLocation(location);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
