/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.Drivers;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class DriversRecord extends UpdatableRecordImpl<DriversRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.drivers.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.drivers.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.drivers.first_name</code>.
     */
    public void setFirstName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.drivers.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.drivers.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.drivers.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.drivers.nationality</code>.
     */
    public void setNationality(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.drivers.nationality</code>.
     */
    public String getNationality() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.drivers.hometown</code>.
     */
    public void setHometown(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.drivers.hometown</code>.
     */
    public String getHometown() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.drivers.license_type</code>.
     */
    public void setLicenseType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.drivers.license_type</code>.
     */
    public String getLicenseType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.drivers.external_id</code>.
     */
    public void setExternalId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.drivers.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DriversRecord
     */
    public DriversRecord() {
        super(Drivers.DRIVERS);
    }

    /**
     * Create a detached, initialised DriversRecord
     */
    public DriversRecord(Long id, String firstName, String lastName, String nationality, String hometown, String licenseType, String externalId) {
        super(Drivers.DRIVERS);

        setId(id);
        setFirstName(firstName);
        setLastName(lastName);
        setNationality(nationality);
        setHometown(hometown);
        setLicenseType(licenseType);
        setExternalId(externalId);
        resetChangedOnNotNull();
    }
}
