/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.Events;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.events.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.events.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.events.series_id</code>.
     */
    public void setSeriesId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.events.series_id</code>.
     */
    public Long getSeriesId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.events.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.events.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.events.year</code>.
     */
    public void setYear(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.events.year</code>.
     */
    public Integer getYear() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.events.start_date</code>.
     */
    public void setStartDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.events.start_date</code>.
     */
    public LocalDate getStartDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.events.end_date</code>.
     */
    public void setEndDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.events.end_date</code>.
     */
    public LocalDate getEndDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>public.events.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.events.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(Long id, Long seriesId, String name, Integer year, LocalDate startDate, LocalDate endDate, String description) {
        super(Events.EVENTS);

        setId(id);
        setSeriesId(seriesId);
        setName(name);
        setYear(year);
        setStartDate(startDate);
        setEndDate(endDate);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
