/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.Manufacturers;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ManufacturersRecord extends UpdatableRecordImpl<ManufacturersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.manufacturers.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.manufacturers.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.manufacturers.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.manufacturers.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.manufacturers.country</code>.
     */
    public void setCountry(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.manufacturers.country</code>.
     */
    public String getCountry() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManufacturersRecord
     */
    public ManufacturersRecord() {
        super(Manufacturers.MANUFACTURERS);
    }

    /**
     * Create a detached, initialised ManufacturersRecord
     */
    public ManufacturersRecord(Long id, String name, String country) {
        super(Manufacturers.MANUFACTURERS);

        setId(id);
        setName(name);
        setCountry(country);
        resetChangedOnNotNull();
    }
}
