/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.ImportJobs;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ImportJobsRecord extends UpdatableRecordImpl<ImportJobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.import_jobs.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.import_jobs.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.import_jobs.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.import_jobs.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.import_jobs.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.import_jobs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.import_jobs.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.import_jobs.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.import_jobs.started_at</code>.
     */
    public void setStartedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.import_jobs.started_at</code>.
     */
    public LocalDateTime getStartedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.import_jobs.ended_at</code>.
     */
    public void setEndedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.import_jobs.ended_at</code>.
     */
    public LocalDateTime getEndedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.import_jobs.error</code>.
     */
    public void setError(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.import_jobs.error</code>.
     */
    public String getError() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.import_jobs.source_url</code>.
     */
    public void setSourceUrl(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.import_jobs.source_url</code>.
     */
    public String getSourceUrl() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImportJobsRecord
     */
    public ImportJobsRecord() {
        super(ImportJobs.IMPORT_JOBS);
    }

    /**
     * Create a detached, initialised ImportJobsRecord
     */
    public ImportJobsRecord(Integer id, String status, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime startedAt, LocalDateTime endedAt, String error, String sourceUrl) {
        super(ImportJobs.IMPORT_JOBS);

        setId(id);
        setStatus(status);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setStartedAt(startedAt);
        setEndedAt(endedAt);
        setError(error);
        setSourceUrl(sourceUrl);
        resetChangedOnNotNull();
    }
}
