/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.Results;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ResultsRecord extends UpdatableRecordImpl<ResultsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.results.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.results.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.results.session_id</code>.
     */
    public void setSessionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.results.session_id</code>.
     */
    public Long getSessionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.results.car_entry_id</code>.
     */
    public void setCarEntryId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.results.car_entry_id</code>.
     */
    public Long getCarEntryId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.results.car_number</code>.
     */
    public void setCarNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.results.car_number</code>.
     */
    public String getCarNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.results.tires</code>.
     */
    public void setTires(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.results.tires</code>.
     */
    public String getTires() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.results.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.results.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.results.laps</code>.
     */
    public void setLaps(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.results.laps</code>.
     */
    public Integer getLaps() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.results.total_time</code>.
     */
    public void setTotalTime(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.results.total_time</code>.
     */
    public String getTotalTime() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.results.gap_first</code>.
     */
    public void setGapFirst(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.results.gap_first</code>.
     */
    public String getGapFirst() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.results.gap_previous</code>.
     */
    public void setGapPrevious(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.results.gap_previous</code>.
     */
    public String getGapPrevious() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.results.fl_lapnum</code>.
     */
    public void setFlLapnum(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.results.fl_lapnum</code>.
     */
    public Integer getFlLapnum() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.results.fl_time</code>.
     */
    public void setFlTime(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.results.fl_time</code>.
     */
    public String getFlTime() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.results.fl_kph</code>.
     */
    public void setFlKph(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.results.fl_kph</code>.
     */
    public BigDecimal getFlKph() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>public.results.position</code>.
     */
    public void setPosition(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.results.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ResultsRecord
     */
    public ResultsRecord() {
        super(Results.RESULTS);
    }

    /**
     * Create a detached, initialised ResultsRecord
     */
    public ResultsRecord(Long id, Long sessionId, Long carEntryId, String carNumber, String tires, String status, Integer laps, String totalTime, String gapFirst, String gapPrevious, Integer flLapnum, String flTime, BigDecimal flKph, Integer position) {
        super(Results.RESULTS);

        setId(id);
        setSessionId(sessionId);
        setCarEntryId(carEntryId);
        setCarNumber(carNumber);
        setTires(tires);
        setStatus(status);
        setLaps(laps);
        setTotalTime(totalTime);
        setGapFirst(gapFirst);
        setGapPrevious(gapPrevious);
        setFlLapnum(flLapnum);
        setFlTime(flTime);
        setFlKph(flKph);
        setPosition(position);
        resetChangedOnNotNull();
    }
}
