/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables.records;


import com.arjunakankipati.racingstatanalysis.jooq.tables.Sessions;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SessionsRecord extends UpdatableRecordImpl<SessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sessions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sessions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.sessions.event_id</code>.
     */
    public void setEventId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sessions.event_id</code>.
     */
    public Long getEventId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.sessions.circuit_id</code>.
     */
    public void setCircuitId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sessions.circuit_id</code>.
     */
    public Long getCircuitId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.sessions.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sessions.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sessions.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sessions.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sessions.start_datetime</code>.
     */
    public void setStartDatetime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.sessions.start_datetime</code>.
     */
    public LocalDateTime getStartDatetime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.sessions.duration_seconds</code>.
     */
    public void setDurationSeconds(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.sessions.duration_seconds</code>.
     */
    public Integer getDurationSeconds() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionsRecord
     */
    public SessionsRecord() {
        super(Sessions.SESSIONS);
    }

    /**
     * Create a detached, initialised SessionsRecord
     */
    public SessionsRecord(Long id, Long eventId, Long circuitId, String name, String type, LocalDateTime startDatetime, Integer durationSeconds) {
        super(Sessions.SESSIONS);

        setId(id);
        setEventId(eventId);
        setCircuitId(circuitId);
        setName(name);
        setType(type);
        setStartDatetime(startDatetime);
        setDurationSeconds(durationSeconds);
        resetChangedOnNotNull();
    }
}
