/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq;


import com.arjunakankipati.racingstatanalysis.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.car_drivers</code>.
     */
    public final CarDrivers CAR_DRIVERS = CarDrivers.CAR_DRIVERS;

    /**
     * The table <code>public.car_entries</code>.
     */
    public final CarEntries CAR_ENTRIES = CarEntries.CAR_ENTRIES;

    /**
     * The table <code>public.car_models</code>.
     */
    public final CarModels CAR_MODELS = CarModels.CAR_MODELS;

    /**
     * The table <code>public.circuits</code>.
     */
    public final Circuits CIRCUITS = Circuits.CIRCUITS;

    /**
     * The table <code>public.classes</code>.
     */
    public final Classes CLASSES = Classes.CLASSES;

    /**
     * The table <code>public.drivers</code>.
     */
    public final Drivers DRIVERS = Drivers.DRIVERS;

    /**
     * The table <code>public.events</code>.
     */
    public final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.laps</code>.
     */
    public final Laps LAPS = Laps.LAPS;

    /**
     * The table <code>public.manufacturers</code>.
     */
    public final Manufacturers MANUFACTURERS = Manufacturers.MANUFACTURERS;

    /**
     * The table <code>public.sectors</code>.
     */
    public final Sectors SECTORS = Sectors.SECTORS;

    /**
     * The table <code>public.series</code>.
     */
    public final Series SERIES = Series.SERIES;

    /**
     * The table <code>public.sessions</code>.
     */
    public final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>public.teams</code>.
     */
    public final Teams TEAMS = Teams.TEAMS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
                CarDrivers.CAR_DRIVERS,
                CarEntries.CAR_ENTRIES,
                CarModels.CAR_MODELS,
                Circuits.CIRCUITS,
                Classes.CLASSES,
                Drivers.DRIVERS,
                Events.EVENTS,
                FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
                Laps.LAPS,
                Manufacturers.MANUFACTURERS,
                Sectors.SECTORS,
                Series.SERIES,
                Sessions.SESSIONS,
                Teams.TEAMS
        );
    }
}
