/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq;


import com.arjunakankipati.racingstatanalysis.jooq.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_CAR_DRIVERS_CAR_ID = Internal.createIndex(DSL.name("idx_car_drivers_car_id"), CarDrivers.CAR_DRIVERS, new OrderField[] { CarDrivers.CAR_DRIVERS.CAR_ID }, false);
    public static final Index IDX_CAR_ENTRIES_SESSION_CLASS = Internal.createIndex(DSL.name("idx_car_entries_session_class"), CarEntries.CAR_ENTRIES, new OrderField[] { CarEntries.CAR_ENTRIES.SESSION_ID, CarEntries.CAR_ENTRIES.CLASS_ID }, false);
    public static final Index IDX_CAR_ENTRIES_TEAM_ID = Internal.createIndex(DSL.name("idx_car_entries_team_id"), CarEntries.CAR_ENTRIES, new OrderField[] { CarEntries.CAR_ENTRIES.TEAM_ID }, false);
    public static final Index IDX_CLASSES_SERIES_ID = Internal.createIndex(DSL.name("idx_classes_series_id"), Classes.CLASSES, new OrderField[] { Classes.CLASSES.SERIES_ID }, false);
    public static final Index IDX_EVENTS_SERIES_ID_YEAR = Internal.createIndex(DSL.name("idx_events_series_id_year"), Events.EVENTS, new OrderField[] { Events.EVENTS.SERIES_ID, Events.EVENTS.YEAR }, false);
    public static final Index IDX_IMPORT_JOBS_STATUS = Internal.createIndex(DSL.name("idx_import_jobs_status"), ImportJobs.IMPORT_JOBS, new OrderField[]{ImportJobs.IMPORT_JOBS.STATUS}, false);
    public static final Index IDX_LAPS_CAR_VALID_TIME = Internal.createIndex(DSL.name("idx_laps_car_valid_time"), Laps.LAPS, new OrderField[] { Laps.LAPS.CAR_ID, Laps.LAPS.IS_VALID, Laps.LAPS.LAP_TIME_SECONDS }, false);
    public static final Index IDX_LAPS_DRIVER_VALID_TIME = Internal.createIndex(DSL.name("idx_laps_driver_valid_time"), Laps.LAPS, new OrderField[] { Laps.LAPS.DRIVER_ID, Laps.LAPS.IS_VALID, Laps.LAPS.LAP_TIME_SECONDS }, false);
    public static final Index IDX_SESSIONS_EVENT_ID = Internal.createIndex(DSL.name("idx_sessions_event_id"), Sessions.SESSIONS, new OrderField[] { Sessions.SESSIONS.EVENT_ID }, false);
}
