/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq;


import com.arjunakankipati.racingstatanalysis.jooq.tables.*;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.car_drivers</code>.
     */
    public static final CarDrivers CAR_DRIVERS = CarDrivers.CAR_DRIVERS;

    /**
     * The table <code>public.car_entries</code>.
     */
    public static final CarEntries CAR_ENTRIES = CarEntries.CAR_ENTRIES;

    /**
     * The table <code>public.car_models</code>.
     */
    public static final CarModels CAR_MODELS = CarModels.CAR_MODELS;

    /**
     * The table <code>public.circuits</code>.
     */
    public static final Circuits CIRCUITS = Circuits.CIRCUITS;

    /**
     * The table <code>public.classes</code>.
     */
    public static final Classes CLASSES = Classes.CLASSES;

    /**
     * The table <code>public.drivers</code>.
     */
    public static final Drivers DRIVERS = Drivers.DRIVERS;

    /**
     * The table <code>public.events</code>.
     */
    public static final Events EVENTS = Events.EVENTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.import_jobs</code>.
     */
    public static final ImportJobs IMPORT_JOBS = ImportJobs.IMPORT_JOBS;

    /**
     * The table <code>public.laps</code>.
     */
    public static final Laps LAPS = Laps.LAPS;

    /**
     * The table <code>public.manufacturers</code>.
     */
    public static final Manufacturers MANUFACTURERS = Manufacturers.MANUFACTURERS;

    /**
     * The table <code>public.results</code>.
     */
    public static final Results RESULTS = Results.RESULTS;

    /**
     * The table <code>public.results_drivers</code>.
     */
    public static final ResultsDrivers RESULTS_DRIVERS = ResultsDrivers.RESULTS_DRIVERS;

    /**
     * The table <code>public.sectors</code>.
     */
    public static final Sectors SECTORS = Sectors.SECTORS;

    /**
     * The table <code>public.series</code>.
     */
    public static final Series SERIES = Series.SERIES;

    /**
     * The table <code>public.sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>public.teams</code>.
     */
    public static final Teams TEAMS = Teams.TEAMS;
}
