/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables;


import com.arjunakankipati.racingstatanalysis.jooq.Keys;
import com.arjunakankipati.racingstatanalysis.jooq.Public;
import com.arjunakankipati.racingstatanalysis.jooq.tables.CarDrivers.CarDriversPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.Classes.ClassesPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.Laps.LapsPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.Manufacturers.ManufacturersPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.Sessions.SessionsPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.Teams.TeamsPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.records.CarsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Cars extends TableImpl<CarsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.cars</code>
     */
    public static final Cars CARS = new Cars();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CarsRecord> getRecordType() {
        return CarsRecord.class;
    }

    /**
     * The column <code>public.cars.id</code>.
     */
    public final TableField<CarsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.cars.session_id</code>.
     */
    public final TableField<CarsRecord, Long> SESSION_ID = createField(DSL.name("session_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.cars.team_id</code>.
     */
    public final TableField<CarsRecord, Long> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.cars.class_id</code>.
     */
    public final TableField<CarsRecord, Long> CLASS_ID = createField(DSL.name("class_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.cars.manufacturer_id</code>.
     */
    public final TableField<CarsRecord, Long> MANUFACTURER_ID = createField(DSL.name("manufacturer_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.cars.number</code>.
     */
    public final TableField<CarsRecord, String> NUMBER = createField(DSL.name("number"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.cars.model</code>.
     */
    public final TableField<CarsRecord, String> MODEL = createField(DSL.name("model"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.cars.tire_supplier</code>.
     */
    public final TableField<CarsRecord, String> TIRE_SUPPLIER = createField(DSL.name("tire_supplier"), SQLDataType.VARCHAR(50), this, "");

    private Cars(Name alias, Table<CarsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Cars(Name alias, Table<CarsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.cars</code> table reference
     */
    public Cars(String alias) {
        this(DSL.name(alias), CARS);
    }

    /**
     * Create an aliased <code>public.cars</code> table reference
     */
    public Cars(Name alias) {
        this(alias, CARS);
    }

    /**
     * Create a <code>public.cars</code> table reference
     */
    public Cars() {
        this(DSL.name("cars"), null);
    }

    public <O extends Record> Cars(Table<O> path, ForeignKey<O, CarsRecord> childPath, InverseForeignKey<O, CarsRecord> parentPath) {
        super(path, childPath, parentPath, CARS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CarsPath extends Cars implements Path<CarsRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> CarsPath(Table<O> path, ForeignKey<O, CarsRecord> childPath, InverseForeignKey<O, CarsRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private CarsPath(Name alias, Table<CarsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CarsPath as(String alias) {
            return new CarsPath(DSL.name(alias), this);
        }

        @Override
        public CarsPath as(Name alias) {
            return new CarsPath(alias, this);
        }

        @Override
        public CarsPath as(Table<?> alias) {
            return new CarsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CarsRecord, Long> getIdentity() {
        return (Identity<CarsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CarsRecord> getPrimaryKey() {
        return Keys.CARS_PKEY;
    }

    @Override
    public List<ForeignKey<CarsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CARS__CARS_CLASS_ID_FKEY, Keys.CARS__CARS_MANUFACTURER_ID_FKEY, Keys.CARS__CARS_SESSION_ID_FKEY, Keys.CARS__CARS_TEAM_ID_FKEY);
    }

    private transient ClassesPath _classes;

    /**
     * Get the implicit join path to the <code>public.classes</code> table.
     */
    public ClassesPath classes() {
        if (_classes == null)
            _classes = new ClassesPath(this, Keys.CARS__CARS_CLASS_ID_FKEY, null);

        return _classes;
    }

    private transient ManufacturersPath _manufacturers;

    /**
     * Get the implicit join path to the <code>public.manufacturers</code>
     * table.
     */
    public ManufacturersPath manufacturers() {
        if (_manufacturers == null)
            _manufacturers = new ManufacturersPath(this, Keys.CARS__CARS_MANUFACTURER_ID_FKEY, null);

        return _manufacturers;
    }

    private transient SessionsPath _sessions;

    /**
     * Get the implicit join path to the <code>public.sessions</code> table.
     */
    public SessionsPath sessions() {
        if (_sessions == null)
            _sessions = new SessionsPath(this, Keys.CARS__CARS_SESSION_ID_FKEY, null);

        return _sessions;
    }

    private transient TeamsPath _teams;

    /**
     * Get the implicit join path to the <code>public.teams</code> table.
     */
    public TeamsPath teams() {
        if (_teams == null)
            _teams = new TeamsPath(this, Keys.CARS__CARS_TEAM_ID_FKEY, null);

        return _teams;
    }

    private transient CarDriversPath _carDrivers;

    /**
     * Get the implicit to-many join path to the <code>public.car_drivers</code>
     * table
     */
    public CarDriversPath carDrivers() {
        if (_carDrivers == null)
            _carDrivers = new CarDriversPath(this, null, Keys.CAR_DRIVERS__CAR_DRIVERS_CAR_ID_FKEY.getInverseKey());

        return _carDrivers;
    }

    private transient LapsPath _laps;

    /**
     * Get the implicit to-many join path to the <code>public.laps</code> table
     */
    public LapsPath laps() {
        if (_laps == null)
            _laps = new LapsPath(this, null, Keys.LAPS__LAPS_CAR_ID_FKEY.getInverseKey());

        return _laps;
    }

    @Override
    public Cars as(String alias) {
        return new Cars(DSL.name(alias), this);
    }

    @Override
    public Cars as(Name alias) {
        return new Cars(alias, this);
    }

    @Override
    public Cars as(Table<?> alias) {
        return new Cars(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cars rename(String name) {
        return new Cars(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cars rename(Name name) {
        return new Cars(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cars rename(Table<?> name) {
        return new Cars(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars where(Condition condition) {
        return new Cars(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cars where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cars where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cars where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Cars where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Cars whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
