/*
 * This file is generated by jOOQ.
 */
package com.arjunakankipati.racingstatanalysis.jooq.tables;


import com.arjunakankipati.racingstatanalysis.jooq.Keys;
import com.arjunakankipati.racingstatanalysis.jooq.Public;
import com.arjunakankipati.racingstatanalysis.jooq.tables.Cars.CarsPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.Circuits.CircuitsPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.Events.EventsPath;
import com.arjunakankipati.racingstatanalysis.jooq.tables.records.SessionsRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Sessions extends TableImpl<SessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.sessions</code>
     */
    public static final Sessions SESSIONS = new Sessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SessionsRecord> getRecordType() {
        return SessionsRecord.class;
    }

    /**
     * The column <code>public.sessions.id</code>.
     */
    public final TableField<SessionsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.sessions.event_id</code>.
     */
    public final TableField<SessionsRecord, Long> EVENT_ID = createField(DSL.name("event_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.sessions.circuit_id</code>.
     */
    public final TableField<SessionsRecord, Long> CIRCUIT_ID = createField(DSL.name("circuit_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.sessions.name</code>.
     */
    public final TableField<SessionsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.sessions.type</code>.
     */
    public final TableField<SessionsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.sessions.start_datetime</code>.
     */
    public final TableField<SessionsRecord, LocalDateTime> START_DATETIME = createField(DSL.name("start_datetime"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.sessions.duration_seconds</code>.
     */
    public final TableField<SessionsRecord, Integer> DURATION_SECONDS = createField(DSL.name("duration_seconds"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sessions.weather_air_temp</code>.
     */
    public final TableField<SessionsRecord, BigDecimal> WEATHER_AIR_TEMP = createField(DSL.name("weather_air_temp"), SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>public.sessions.weather_track_temp</code>.
     */
    public final TableField<SessionsRecord, BigDecimal> WEATHER_TRACK_TEMP = createField(DSL.name("weather_track_temp"), SQLDataType.NUMERIC(5, 2), this, "");

    /**
     * The column <code>public.sessions.weather_condition</code>.
     */
    public final TableField<SessionsRecord, String> WEATHER_CONDITION = createField(DSL.name("weather_condition"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.sessions.report_message</code>.
     */
    public final TableField<SessionsRecord, String> REPORT_MESSAGE = createField(DSL.name("report_message"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.sessions.import_url</code>.
     */
    public final TableField<SessionsRecord, String> IMPORT_URL = createField(DSL.name("import_url"), SQLDataType.VARCHAR(2048), this, "");

    /**
     * The column <code>public.sessions.import_timestamp</code>.
     */
    public final TableField<SessionsRecord, LocalDateTime> IMPORT_TIMESTAMP = createField(DSL.name("import_timestamp"), SQLDataType.LOCALDATETIME(6), this, "");

    private Sessions(Name alias, Table<SessionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Sessions(Name alias, Table<SessionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.sessions</code> table reference
     */
    public Sessions(String alias) {
        this(DSL.name(alias), SESSIONS);
    }

    /**
     * Create an aliased <code>public.sessions</code> table reference
     */
    public Sessions(Name alias) {
        this(alias, SESSIONS);
    }

    /**
     * Create a <code>public.sessions</code> table reference
     */
    public Sessions() {
        this(DSL.name("sessions"), null);
    }

    public <O extends Record> Sessions(Table<O> path, ForeignKey<O, SessionsRecord> childPath, InverseForeignKey<O, SessionsRecord> parentPath) {
        super(path, childPath, parentPath, SESSIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SessionsPath extends Sessions implements Path<SessionsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SessionsPath(Table<O> path, ForeignKey<O, SessionsRecord> childPath, InverseForeignKey<O, SessionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SessionsPath(Name alias, Table<SessionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SessionsPath as(String alias) {
            return new SessionsPath(DSL.name(alias), this);
        }

        @Override
        public SessionsPath as(Name alias) {
            return new SessionsPath(alias, this);
        }

        @Override
        public SessionsPath as(Table<?> alias) {
            return new SessionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SessionsRecord, Long> getIdentity() {
        return (Identity<SessionsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SessionsRecord> getPrimaryKey() {
        return Keys.SESSIONS_PKEY;
    }

    @Override
    public List<ForeignKey<SessionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SESSIONS__SESSIONS_CIRCUIT_ID_FKEY, Keys.SESSIONS__SESSIONS_EVENT_ID_FKEY);
    }

    private transient CircuitsPath _circuits;

    /**
     * Get the implicit join path to the <code>public.circuits</code> table.
     */
    public CircuitsPath circuits() {
        if (_circuits == null)
            _circuits = new CircuitsPath(this, Keys.SESSIONS__SESSIONS_CIRCUIT_ID_FKEY, null);

        return _circuits;
    }

    private transient EventsPath _events;

    /**
     * Get the implicit join path to the <code>public.events</code> table.
     */
    public EventsPath events() {
        if (_events == null)
            _events = new EventsPath(this, Keys.SESSIONS__SESSIONS_EVENT_ID_FKEY, null);

        return _events;
    }

    private transient CarsPath _cars;

    /**
     * Get the implicit to-many join path to the <code>public.cars</code> table
     */
    public CarsPath cars() {
        if (_cars == null)
            _cars = new CarsPath(this, null, Keys.CARS__CARS_SESSION_ID_FKEY.getInverseKey());

        return _cars;
    }

    @Override
    public Sessions as(String alias) {
        return new Sessions(DSL.name(alias), this);
    }

    @Override
    public Sessions as(Name alias) {
        return new Sessions(alias, this);
    }

    @Override
    public Sessions as(Table<?> alias) {
        return new Sessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sessions rename(String name) {
        return new Sessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sessions rename(Name name) {
        return new Sessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Sessions rename(Table<?> name) {
        return new Sessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions where(Condition condition) {
        return new Sessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Sessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Sessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
